### ISSUE TITLE
lodash.assign dependency

### ISSUE THREAD

**Issue by vadimi** [tracker1/gulp-footer#2]
Hi, any chance you can replace `lodash.assign` dependency with `object-assign` as in `gulp-header` - I'm having problems using it on Windows (too much subfolders in `lodash.assign` and Windows doesn't like more than 260 characters). Thanks.

**Comment by jdalton** [comment]
Just a heads up. [lodash v3](https://github.com/lodash/lodash/releases/tag/3.0.0) has significantly reduced the dep graphs of its modularized packages:
```
lodash.assign@3.0.0
├─┬ lodash._baseassign@3.0.1
│ ├── lodash._basecopy@3.0.0
│ └─┬ lodash.keys@3.0.3
│   ├── lodash.isarguments@3.0.0
│   ├── lodash.isarray@3.0.0
│   └── lodash.isnative@3.0.0
└─┬ lodash._createassigner@3.0.0
  ├── lodash._bindcallback@3.0.0
  └── lodash._isiterateecall@3.0.1
```

There's even a simplified form:
```
lodash._baseassign@3.0.1
├── lodash._basecopy@3.0.0
└─┬ lodash.keys@3.0.3
  ├── lodash.isarguments@3.0.0
  ├── lodash.isarray@3.0.0
  └── lodash.isnative@3.0.0
```

**Comment by tracker1** [comment]
lodash.assign isn't used anymore, but there's other lodash dependencies... npm has long since been updated to mitigate this issue... closing.
