### ISSUE TITLE
Node Versions for Travis CI are Deprecated & Failing

### ISSUE THREAD

**Issue by simonua** [tracker1/gulp-footer#7]
Versions 0.10 and 0.11 are long deprecated. CI tests are failing. The currently-supported LTS verions are [4, 6, and 8](https://github.com/nodejs/Release#release-schedule).

**Comment by tracker1** [comment]
Thanks for the patch, committed, updated the contributors, and published.

**Comment by simonua** [comment]
Thank you, @tracker1! I appreciate you.
